javascript/manga/src/zh/copymanga.js
javascript/manga/src/zh/dmzj.js
javascript/manga/src/zh/jmcomic.js

#35 jmcomic
#50 dmzj and copymanga

add dmzj,copymanga,jmcomic

---

javascript/anime/src/de/aniworld.js

- Implemented a vidoza extractor
- Implemented a temporary doodstream extractor until the one in the application is fixed.
- Changed quality from `${hoster} ${language}` to `${language} - ${hoster}` for better sorting and readability

AniWorld - Doodstream & Vidoza Fix

---

javascript/anime/src/de/aniworld.js
javascript/anime/src/es/animefenix.js
javascript/anime/src/es/jkanime.js
javascript/anime/src/es/tioanime.js
javascript/manga/src/all/mangafire.js

- New Source: TioAnime source (es)
- New Source: AnimeFenix source (es)
- New Source: JKAnime source (es)
- Aniworld: Async loading for getVideoList and getDetail.
- Aniworld: Changed headers in getVideoList which helps load times (a lot).
- Mangafire: changed a query name
- Mangafire: Search sometimes failed because filters were empty. I got this on android. And some other user also stated having problems with search.
- Implemented new video extractors and helper functions in a "library", used in all three new extensions.
- Some way to import a file from the extension repo would help.
- A core library which does not depend on the app being updated would be awesome!

Add TioAnime, AnimeFenix and JKAnime + Updates to Mangafire and Aniworld

---

javascript/anime/src/de/aniworld.js
javascript/anime/src/es/animefenix.js
javascript/anime/src/es/jkanime.js
javascript/anime/src/es/tioanime.js

AniWorld
- New Host: SpeedFiles
- New Host: Filemoon
- Better Sorting for preferences
AnimeFenix:
- Added possible status string
JKAnime
- Get Studios
TioAnime
- Fix hasNextPage
Helper library
- Add new host: SpeedFiles
- Add new String function: reverse, swapcase

AniWorld, AnimeFenix, JKAnime and TioAnime: New host, fixes and helper lib update

---

javascript/anime/src/es/animefenix.js
javascript/anime/src/es/jkanime.js
javascript/anime/src/es/tioanime.js
javascript/anime/src/it/animeworld.js
javascript/manga/src/it/mangaworld.js

New Source:
- MangaWorld
JKAnime, TioAnime, AnimeFenix and AnimeWorld:
- Add await before this.parseAnimeList for readability

New Source: MangaWorld (IT) + Fixes

---

javascript/anime/src/all/autoembed.js

Extension for https://autoembed.cc/ , https://watch.autoembed.cc/

New Source: Autoembed (All)

---

javascript/anime/src/all/autoembed.js

* Added list priority - People can chose if they want movie or series to show first
* Modified content link - Updated content link from imdb to autoembed

extension(Autoembed): Updates

---

javascript/manga/src/en/mangapill.js

extension for https://mangapill.com/

New Source: Mangapill

---

javascript/anime/src/all/autoembed.js

Added following stream source
- 123embed.net
- autoembed.cc ( Indian languages )
- flicky.host ( Indian languages )
- vidapi.click

Added new stream sources for Autoembed 

---

javascript/anime/src/en/sudatchi.js

extesnion for https://sudatchi.com/

New source: Sudatchi

---

javascript/anime/src/de/aniworld.js
javascript/anime/src/de/serienstream.js

Fix formatting issue in description. 
For example:

Update AniWorld & SerienStream

---

javascript/anime/src/all/netflixmirror.js

- Updated extension name to NetMirror
- Added support for Prime
- Added support for 1080p resolution
- Updated cookie logic : 
-- Extract cookie using TV API, eliminating ad wait time
-- Use same cookie for 12 hours
- Load home page faster by not hitting details API for every media

Updated NetflixMirror extension

---

dart/anime/src/it/animesaturn/animesaturn.dart
dart/anime/src/it/animesaturn/source.dart

dart_eval runtime exception: Bad state: No element List.first (dart:core-patch/growable_array.dart:344) SIterable.SgetProperty (package:dart_eval/src/eval/shared/stdlib/core/iterable.dart:609) SList. S getProperty (package:dart-_eval/s/eval/shared/stdib/core/list.dart:900) at < asynchronous gap>
Shangri-La Frontier 2
RUNTIME STATE
6-=-=========
Program offset: 831
Shangri-La Frontier 2
Stack sample: [L7: Instance of "$Future<$Response>', L8: Instance of '$Response', L9: $" «html» <body» «script type="text/javascript" src="/min.js" > </script»<noscript»<h1 style="text-align:center;color:red;"› «strong»Please turn JavaScript on and reload the page.</ strong> </h1></noscripts ‹script»function toNumbers(d)(var e=;d.replace(//g,function(d)epush(parselnt(d,16));return e/function …

animesaturn: fix for this:

---

dart/anime/src/en/animepahe/animepahe.dart

- Added a feature allowing users to set a default audio preference (Japanese or English Dub).
- Default is Japanese, but users can switch to English, and the preference is saved.
- Eliminates the need to manually select an English dub for each new episode, which was a pain point for some users.
- Falls back to Japanese audio if there is no English dub available in kwik stream list.
- Tested with English dub and 1080p quality preference selected on older anime that are fully dubbed, which works fine. 
- Tested on currently airing anime which play English Dub fine, then switches back to Japanese audio automatically when that episode doesn't have an English dub.

Update animepahe.dart. Add feature: Preferred audio selection (jpn/eng).

---

dart/anime/src/en/animepahe/source.dart

- Update animepahe version constant to 0.0.5 after implementing Preferred Audio Preference feature #143

Update animepahe source.dart to version 0.0.5

---

javascript/anime/src/all/netflixmirror.js

* Added stream validation
* Added stream extraction source

Update: Netmirror

---

javascript/anime/src/en/aniplay.js

- Fixed Yuki provider = refactor subtitle logic
- Added Pahe provider and remove Anya provider = Anya is unused now and replaced with Pahe

Fix Aniplay

---

javascript/manga/src/en/weebcentral.js

extension for https://weebcentral.com/

New manga source: Weebcentral

---

javascript/anime/src/en/animeparadise.js

Anime extension for https://animeparadise.moe

Source: Animeparadise

---

javascript/anime/src/en/aniplay.js

* Added backup base url
* Added 2 new providers (Maze, Kuro)

extension(aniplay): Updated aniplay

---

javascript/anime/src/all/autoembed.js

* Added multiple subtitle servers
* Added 2 new providers
1. hexa.watch
2. febapi (supports 4K)
* Fix flicky server

Update: Autoembed

---

javascript/anime/src/en/aniplay.js

extension(aniplay): added stream proxy

Fix: Aniplay

---

javascript/anime/src/en/animegg.js

extension for https://animegg.org/

New Source: Animegg

---

javascript/anime/src/en/animez.js

extension for https://animez.org/

New Source: AnimeZ

---

javascript/anime/src/all/soaper.js

Extension for https://soaper.cc (Movies & Series)

New Source: Soaper

---

javascript/anime/src/all/soaper.js

Fix: Soaper

---

javascript/manga/src/all/mangafire.js

Fix: Mangafire

---

javascript/anime/src/all/dramacool.js

extension for https://dramacool.com.tr/

New Source: Dramacool

---

javascript/manga/src/ar/teamx.js

manga extension for https://olympustaff.com/
Related to #21

New Source: TeamX

---

dart/anime/multisrc/zorotheme/sources.dart
dart/anime/multisrc/zorotheme/zorotheme.dart

Used a RegExp to reflect any potential TLD change

HiAnime - Fix serverType

---

javascript/anime/src/en/gojo.js

Extension for source: https://gojo.wtf/

New Source: Gojo

---

javascript/anime/src/en/aniplay.js

* Added ability to override next_action value

Update: Aniplay

---

javascript/anime/src/de/aniworld.js
javascript/anime/src/de/serienstream.js

AniWorld + SerienStream filter out pseudo genres

---

javascript/anime/src/en/animekai.js

Extension for https://animekai.to/ , https://animekai.bz/

New source: AnimeKai

---

javascript/manga/src/en/readcomiconline.js

Extension for https://readcomiconline.li/
closes #27

New source: ReadComicOnline

---

javascript/anime/src/all/netflixmirror.js

* Use only TV domain to populate details
* Fix subtitle issue

Rework: Netmirror

---

javascript/anime/src/all/autoembed.js
javascript/anime/src/all/soaper.js
javascript/anime/src/en/animegg.js
javascript/anime/src/en/animeonsen.js
javascript/anime/src/en/animeparadise.js
javascript/anime/src/en/animez.js
javascript/anime/src/en/gojo.js
javascript/anime/src/en/sudatchi.js
javascript/manga/src/en/mangapill.js
javascript/manga/src/en/readcomiconline.js

Fixes refresh contain issue in extensions I made

fix: Refresh contain issue

---

dart/manga/src/en/mangapark/mangapark.dart
dart/manga/src/en/mangapark/source.dart

url was wrong, should work this way

Update source.dart - URL fix

---

javascript/manga/src/all/mangafire.js

Fix page extraction for mangas with no volumes.

Fix Mangafire

---

dart/manga/multisrc/mangareader/src/en/suryascans/suryascans.dart

fix(SuryaScans): Update Surya Scans source URL
